New_HJCRSA_App/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), 
    
]

main_app/urls.py
from django.urls import path
from . import views
from .views import ActivityLogView
from django.contrib.auth import views as auth_views
from .views import login_view
from .views import login_view, home_view

urlpatterns = [
    
    # Add forms
    path('member/add/', views.add_main_member, name='add_main_member'),
    path('dependent/add/', views.add_dependent, name='add_dependent'),
    path('treasury/add/', views.add_treasury, name='add_treasury'),
    path('treasury-dep/add/', views.add_treasury_dep, name='add_treasury_dep'),
    
    # List views
    path('members/', views.member_list, name='member_list'),
    path('dependents/', views.dependent_list, name='dependent_list'),
    path('treasury/', views.treasury_list, name='treasury_list'),
    path('treasury-dep/', views.treasury_dep_list, name='treasury_dep_list'),
    path('activity-log/', ActivityLogView.as_view(), name='activity_log'),
    path('member/<int:pk>/edit/', views.MemberUpdateView.as_view(), name='edit_member'),
    path('api/member/<int:card_number>/payments/', views.member_payments, name='member_payments'),
    path('api/member/<int:card_number>/dependents/', views.member_dependents, name='member_dependents'),
    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('home/', views.home_view, name='home'),
    path('validate-card-number/', views.validate_card_number, name='validate_card_number'),
    path('api/member/<str:branch_member_number>/upload-picture/', views.upload_member_picture, name='upload_member_picture'),
    path('validate-card-number-add/', views.validate_card_number_add, name='validate_card_number_add'),
    path('api/dependent/<int:dependent_id>/payments/', views.dependent_payments, name='dependent_payments'),
    path('api/dependent/<int:dependent_id>/payments/', views.dependent_payments, name='dependent_payments'),
    path('signup/', views.signup_view, name='signup'),
    path('api/gender-distribution/', views.get_gender_distribution, name='gender_distribution'),
    path('upload-picture/', views.upload_picture, name='upload_picture'),





    
]

main_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


class MainMembers(models.Model):
    branch_member_number = models.CharField(max_length=255, null=True, blank=True, editable=False)
    card_number = models.IntegerField(db_column='Card_Number', primary_key=True)
    name = models.CharField(db_column='Name', max_length=100)
    surname = models.CharField(db_column='Surname', max_length=100)
    address = models.CharField(db_column='Address', max_length=100)
    phone_number = models.CharField(db_column='Phone_Number', max_length=45, blank=True, null=True)
    branch = models.CharField(db_column='Branch', max_length=100)
    gender = models.CharField(db_column='Gender', max_length=45)
    registration_year = models.IntegerField(db_column='Registration_Year', blank=True, null=True)
    number_of_dependants = models.IntegerField(db_column='Number_Of_Dependants')
    branch_member_number = models.CharField(db_column='Branch_Member_Number', max_length=10, unique=True)
    church_title = models.CharField(max_length=45, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'Main_Members'
        unique_together = (('card_number', 'name', 'surname'),)


class Dependents(models.Model):
    iddependents = models.AutoField(db_column='idDependents', primary_key=True)  # Field name made lowercase.
    card_number = models.IntegerField(db_column='Card_Number')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=100)  # Field name made lowercase.
    surname = models.CharField(db_column='Surname', max_length=100)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Dependents'


class Treasury(models.Model):
    idtreasury = models.AutoField(db_column='idTreasury', primary_key=True)  # Field name made lowercase.
    idmain_member = models.IntegerField(db_column='idMain_Member')  # Field name made lowercase.
    fund = models.CharField(db_column='Fund', max_length=45)  # Field name made lowercase.
    amount = models.IntegerField(db_column='Amount')  # Field name made lowercase.
    fund_date_year = models.IntegerField(db_column='Fund_Date_Year')  # Field name made lowercase.
    fund_date_month = models.CharField(db_column='Fund_Date_Month', max_length=50)  # Field name made lowercase.
    receipt_number = models.IntegerField(db_column='Receipt_Number')  # Field name made lowercase.
    payment_date = models.DateField(db_column='Payment_Date')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Treasury'
        unique_together = (('idmain_member', 'fund', 'fund_date_year', 'fund_date_month', 'receipt_number'),)


class TreasuryDep(models.Model):
    idtreasury_dep = models.AutoField(db_column='idTreasury_Dep', primary_key=True)  # Field name made lowercase.
    card_number = models.IntegerField(db_column='Card_Number')  # Field name made lowercase.
    dependent_id = models.IntegerField(db_column='Dependent_ID')  # Field name made lowercase.
    fund = models.CharField(db_column='Fund', max_length=50)  # Field name made lowercase.
    amount = models.IntegerField(db_column='Amount')  # Field name made lowercase.
    fund_date_year = models.IntegerField(db_column='Fund_Date_Year')  # Field name made lowercase.
    fund_date_month = models.IntegerField(db_column='Fund_Date_Month')  # Field name made lowercase.
    reciept_number = models.IntegerField(db_column='Reciept_Number')  # Field name made lowercase.
    payment_date = models.DateField(db_column='Payment_Date')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Treasury_Dep'
        
        


class ActivityLog(models.Model):
    ACTIONS = (
        ('CREATE', 'Created'),
        ('UPDATE', 'Updated'),
        ('DELETE', 'Deleted'),
        ('LOGIN', 'Logged In'),
        ('PAYMENT', 'Payment Made'),
    )

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=ACTIONS)
    timestamp = models.DateTimeField(auto_now_add=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    description = models.TextField()

    class Meta:
        ordering = ['-timestamp']
        
class MemberPictures(models.Model):
    id = models.AutoField(primary_key=True)
    branch_member_number = models.OneToOneField(MainMembers, to_field='branch_member_number', db_column='Branch_Member_Number', on_delete=models.CASCADE)
    picture_data = models.BinaryField(null=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'Member_Pictures'
        
class Picture(models.Model):
    image = models.ImageField(upload_to='pictures/')
    upload_date = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"Picture uploaded on {self.upload_date}"

    class Meta:
        ordering = ['-upload_date']
        
class Treasury(models.Model):
    FUND_CHOICES = [
        ('Annual', 'Annual'),
        ('Building Fund', 'Building Fund'),
        ('Thanksgiving', 'Thanksgiving'),
        ('Maintenance', 'Maintenance'),
        ('Blessing', 'Blessing'),
        ('Registration', 'Registration'),
    
    ]

    idtreasury = models.AutoField(db_column='idTreasury', primary_key=True)
    idmain_member = models.IntegerField(db_column='idMain_Member')
    fund = models.CharField(db_column='Fund', max_length=45, choices=FUND_CHOICES)
    amount = models.IntegerField(db_column='Amount')
    fund_date_year = models.IntegerField(db_column='Fund_Date_Year')
    fund_date_month = models.CharField(db_column='Fund_Date_Month', max_length=50)
    receipt_number = models.IntegerField(db_column='Receipt_Number')
    payment_date = models.DateField(db_column='Payment_Date')

    class Meta:
        managed = False
        db_table = 'Treasury'
        unique_together = (('idmain_member', 'fund', 'fund_date_year', 'fund_date_month', 'receipt_number'),)



    def __str__(self):
        return f"{self.user} {self.action} {self.content_type}"
    

main_app/forms.py
from django import forms
from .models import MainMembers, Dependents, Treasury, TreasuryDep

class MainMembersForm(forms.ModelForm):
    class Meta:
        model = MainMembers
        exclude = ['branch_member_number']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(choices=[('M', 'Male'), ('F', 'Female')], attrs={'class': 'form-control'}),
            'branch': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
        }

class DependentsForm(forms.ModelForm):
    class Meta:
        model = Dependents
        exclude = ['idDependents']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'card_number': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class TreasuryForm(forms.ModelForm):
    class Meta:
        model = Treasury
        fields = '__all__'
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'fund': forms.TextInput(attrs={'class': 'form-control'}),
            'payment_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'receipt_number': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class TreasuryDepForm(forms.ModelForm):
    class Meta:
        model = TreasuryDep
        fields = '__all__'
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'fund': forms.TextInput(attrs={'class': 'form-control'}),
            'payment_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'receipt_number': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        
# main_app/forms.py

class TreasuryForm(forms.ModelForm):
    FUND_CHOICES = [
        ('Annual', 'Annual'),
        ('Building Fund', 'Building Fund'),
        ('Thanksgiving', 'Thanksgiving'),
        ('Maintenance', 'Maintenance'),
        ('Blessing', 'Blessing'),
        ('Registration', 'Registration'),
    ]
    
    fund = forms.ChoiceField(choices=FUND_CHOICES)
    
    class Meta:
        model = Treasury
        fields = '__all__'

main_app/templates/main_app/add_main_member.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Add Member{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto p-6">
    <!-- Loading Indicator remains unchanged -->
    <div id="validating-indicator" class="hidden fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div class="bg-white p-6 rounded-lg shadow-xl flex items-center space-x-4">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            <span class="text-lg font-semibold text-gray-700">Validating card number...</span>
        </div>
    </div>
    <div id="saving-indicator" class="hidden fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div class="bg-white p-6 rounded-lg shadow-xl flex items-center space-x-4">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            <span class="text-lg font-semibold text-gray-700">Saving member details...</span>
        </div>
    </div>

    <div class="bg-white rounded-xl shadow-lg border border-gray-200">
        <!-- Form Header remains unchanged -->
        <div class="border-b border-gray-200 p-6">
            <div class="flex items-center justify-between">
                <h1 class="text-xl font-semibold text-gray-900">Add New Member</h1>
                <a href="{% url 'member_list' %}" class="text-blue-600 hover:text-blue-700 font-medium">
                    Back to Members
                </a>
            </div>
        </div>

        <!-- Form Content with updated input styling -->
        <div class="p-6">
            <form method="post" class="space-y-6" id="memberForm" action="{% url 'add_main_member' %}">
                {% csrf_token %}
                
                <!-- Main Member Section -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {% for field in form %}
                        {% if field.name != 'branch_member_number' and field.name != 'church_title' %}
                        <div class="space-y-2">
                            <label class="block text-sm font-medium text-gray-700">
                                {{ field.label }}
                            </label>
                            {% if field.name == 'card_number' %}
                            <div class="flex space-x-2">
                                {{ field|add_class:"mt-1 block w-full rounded-md border-2 border-gray-300 bg-white px-3 py-2 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm" }}
                                <button type="button" onclick="validateCardNumber()" class="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700">
                                    Validate
                                </button>
                            </div>
                            {% else %}
                            {{ field|add_class:"mt-1 block w-full rounded-md border-2 border-gray-300 bg-white px-3 py-2 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm" }}
                            {% endif %}
                            {% if field.errors %}
                            <p class="text-red-500 text-xs mt-1">{{ field.errors.0 }}</p>
                            {% endif %}
                        </div>
                        {% endif %}
                        {% endfor %}
                        
                        <!-- Church Title field -->
                        <div class="space-y-2">
                            <label class="block text-sm font-medium text-gray-700">
                                Church Title
                            </label>
                            <select name="church_title" id="id_church_title" class="mt-1 block w-full rounded-md border-2 border-gray-300 bg-white px-3 py-2 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm">
                                <option value="">-- Select Title --</option>
                                <option value="OVERSEERER">OVERSEERER</option>
                                <option value="Reverend">REVEREND</option>
                                <option value="EVANGELIST">EVANGELIST</option>
                                <option value="CONGREGANT">CONGREGANT</option>
                                <option value="MAMKHOKELI">MAMKHOKELI</option>
                            </select>
                        </div>
                    </div>

                <!-- Dependent Section with updated input styling -->
                <div class="mt-8 border-t pt-8">
                    <div class="flex justify-between items-center mb-6">
                        <h2 class="text-xl font-semibold text-gray-900">Add Dependents (Optional)</h2>
                        <button type="button" onclick="addDependentSection()" class="px-4 py-2 bg-green-600 text-white rounded-md text-sm font-medium hover:bg-green-700">
                            Add Another Dependent
                        </button>
                    </div>
                    
                    <div id="dependents-container">
                        <div class="dependent-section mb-6 border p-4 rounded-lg">
                            <div class="flex justify-between items-center mb-4">
                                <h3 class="font-medium text-gray-900">Dependent #1</h3>
                                <button type="button" onclick="toggleDependent(this)" class="text-gray-500 hover:text-gray-700">
                                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                                    </svg>
                                </button>
                            </div>
                            <div class="dependent-fields grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div class="space-y-2">
                                    <label class="block text-sm font-medium text-gray-700">First Name</label>
                                    <input type="text" name="dependent_first_name[]" class="mt-1 block w-full rounded-md border-2 border-gray-300 bg-white px-3 py-2 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm">
                                </div>
                                <div class="space-y-2">
                                    <label class="block text-sm font-medium text-gray-700">Last Name</label>
                                    <input type="text" name="dependent_last_name[]" class="mt-1 block w-full rounded-md border-2 border-gray-300 bg-white px-3 py-2 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Form Actions -->
                <div class="flex justify-end space-x-3 pt-6 border-t border-gray-200">
                    <button type="button" onclick="history.back()" class="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50">
                        Cancel
                    </button>
                    <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700">
                        Save Member
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>

    function showSaving() {
        document.getElementById('saving-indicator').classList.remove('hidden');
    }
    
    function hideSaving() {
        document.getElementById('saving-indicator').classList.add('hidden');
    }
// Add this to your existing JavaScript in the template
document.getElementById('memberForm').addEventListener('submit', function(e) {
    e.preventDefault();
    showSaving();
    
    const formData = new FormData(this);
    
    // Debug: Log form data
    console.log("Form data being submitted:");
    for (let pair of formData.entries()) {
        console.log(pair[0] + ': ' + pair[1]);
    }
    
    fetch(this.action, {
        method: 'POST',
        body: formData,
        headers: {
            'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
        }
    })
    .then(response => response.json())
    .then(data => {
        console.log("Response data:", data);
        if (data.success) {
            // Success - redirect to member list
            window.location.href = "{% url 'member_list' %}";
        } else {
            // Error - show message
            hideSaving();
            if (data.errors) {
                alert("Form validation errors: " + JSON.stringify(data.errors));
            } else if (data.error) {
                alert("Error: " + data.error);
            } else {
                alert("An unknown error occurred");
            }
        }
    })
    .catch(error => {
        console.error('Error:', error);
        hideSaving();
        alert("An error occurred: " + error);
    });
});


    function validateCardNumber() {
        let cardNumber = document.getElementById('id_card_number').value;
        let indicator = document.getElementById('validating-indicator');
        
        indicator.classList.remove('hidden');
        
        fetch(`/validate-card-number-add/?card_number=${cardNumber}`)
            .then(response => response.json())
            .then(data => {
                indicator.classList.add('hidden');
                if (!data.exists) {
                    alert('This card number is already in use. Please enter a different card number.');
                    document.getElementById('id_card_number').value = '';
                    document.getElementById('id_card_number').focus();
                } else {
                    alert('Card number is valid and available!');
                }
            })
            .catch(error => {
                console.error('Error:', error);
                indicator.classList.add('hidden');
            });
    }

    let dependentCount = 1;

    function addDependentSection() {
        dependentCount++;
        const container = document.getElementById('dependents-container');
        const template = document.querySelector('.dependent-section').cloneNode(true);
        
        template.querySelector('h3').textContent = `Dependent #${dependentCount}`;
        template.querySelectorAll('input').forEach(input => input.value = '');
        
        container.appendChild(template);
    }

    function toggleDependent(button) {
        const fields = button.closest('.dependent-section').querySelector('.dependent-fields');
        fields.classList.toggle('hidden');
        
        const path = button.querySelector('path');
        if (fields.classList.contains('hidden')) {
            path.setAttribute('d', 'M9 5l7 7-7 7');
        } else {
            path.setAttribute('d', 'M19 9l-7 7-7-7');
        }
    }
</script>
{% endblock %}

main_app/templates/main_app/add_treasury_dep.html
{% extends 'base.html' %}

{% block title %}Add Treasury Dependent Record{% endblock %}

{% block content %}
<div class="min-h-screen bg-gray-50 py-8">
    <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Loading Indicator -->
        <div id="validating-indicator" class="hidden fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div class="bg-white p-6 rounded-lg shadow-xl flex items-center space-x-4">
                <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                <span class="text-lg font-semibold text-gray-700">Validating card number...</span>
            </div>
        </div>

        <!-- Dependents Modal -->
        <div id="dependentsModal" class="hidden fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div class="bg-white p-6 rounded-lg shadow-xl max-w-md w-full">
                <h3 class="text-lg font-bold mb-4">Select Dependent</h3>
                <div id="dependentsList" class="max-h-60 overflow-y-auto"></div>
                <div class="mt-4 flex justify-end">
                    <button onclick="closeDependentsModal()" class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300">
                        Close
                    </button>
                </div>
            </div>
        </div>

        <!-- Header Section -->
        <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <div class="flex items-center justify-between">
                <h2 class="text-2xl font-bold text-gray-900">Add New Treasury Dependent Record</h2>
                <a href="{% url 'treasury_dep_list' %}" class="text-blue-600 hover:text-blue-800 flex items-center">
                    <svg class="w-5 h-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                    </svg>
                    Back to List
                </a>
            </div>
        </div>

        <!-- Main Form -->
        <div class="bg-white rounded-lg shadow-sm">
            <form method="post" class="space-y-6 p-6">
                {% csrf_token %}
                
                {% for field in form %}
                <div class="form-group">
                    <label class="block text-sm font-medium text-gray-700 mb-2">{{ field.label }}</label>
                    <div class="relative rounded-md shadow-sm">
                        {% if field.name == 'fund' %}
                            <select name="{{ field.name }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">
                                <option value="Annual">Annual</option>
                                <option value="Thanksgiving">Thanksgiving</option>
                            </select>
                        {% elif field.name == 'dependent_id' %}
                            <div class="flex space-x-2">
                                <input type="number" name="dependent_id" required id="id_dependent_id" 
                                       class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">
                                <button type="button" onclick="findDependents()" 
                                        class="mt-1 inline-flex items-center px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                                    <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                                    </svg>
                                    Find Dependents
                                </button>
                            </div>
                        {% else %}
                            {{ field }}
                        {% endif %}
                    </div>
                    {% if field.errors %}
                    <p class="mt-2 text-sm text-red-600">{{ field.errors }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                
                <div class="flex justify-end pt-6 border-t border-gray-200">
                    <button type="submit" class="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
                        </svg>
                        Add Treasury Dependent Record
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
document.getElementById('id_card_number').addEventListener('blur', function() {
    let cardNumber = this.value;
    let indicator = document.getElementById('validating-indicator');
    
    if (cardNumber) {
        indicator.classList.remove('hidden');
        
        fetch(`/validate-card-number/?card_number=${cardNumber}`)
            .then(response => response.json())
            .then(data => {
                indicator.classList.add('hidden');
                if (!data.exists) {
                    alert('Invalid card number. Please enter a valid member card number.');
                    this.value = '';
                    this.focus();
                }
            })
            .catch(error => {
                console.error('Error:', error);
                indicator.classList.add('hidden');
            });
    }
});

function findDependents() {
    const cardNumber = document.getElementById('id_card_number').value;
    if (!cardNumber) {
        alert('Please enter a card number first');
        return;
    }

    const indicator = document.getElementById('validating-indicator');
    const dependentsModal = document.getElementById('dependentsModal');
    const dependentsList = document.getElementById('dependentsList');
    
    indicator.classList.remove('hidden');

    fetch(`/api/member/${cardNumber}/dependents/`)
        .then(response => response.json())
        .then(data => {
            dependentsList.innerHTML = data.map(dep => `
                <div class="p-3 hover:bg-gray-100 cursor-pointer rounded" 
                     onclick="selectDependent(${dep.idDependents})">
                    <div class="font-medium">ID: ${dep.idDependents}</div>
                    <div class="text-sm text-gray-600">${dep.name} ${dep.surname}</div>
                </div>
            `).join('');
            
            if (data.length === 0) {
                dependentsList.innerHTML = '<p class="p-3 text-gray-500">No dependents found</p>';
            }
            
            dependentsModal.classList.remove('hidden');
        })
        .finally(() => {
            indicator.classList.add('hidden');
        });
}

function selectDependent(dependentId) {
    document.getElementById('id_dependent_id').value = dependentId;
    closeDependentsModal();
}

function closeDependentsModal() {
    document.getElementById('dependentsModal').classList.add('hidden');
}

// Close modal when clicking outside
document.getElementById('dependentsModal').addEventListener('click', function(e) {
    if (e.target === this) {
        closeDependentsModal();
    }
});
</script>
{% endblock %}