New_HJCRSA_App/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), 
    
]

main_app/urls.py
from django.urls import path
from . import views
from .views import ActivityLogView
from django.contrib.auth import views as auth_views
from .views import login_view
from .views import login_view, home_view

urlpatterns = [
    
    # Add forms
    path('member/add/', views.add_main_member, name='add_main_member'),
    path('dependent/add/', views.add_dependent, name='add_dependent'),
    path('treasury/add/', views.add_treasury, name='add_treasury'),
    path('treasury-dep/add/', views.add_treasury_dep, name='add_treasury_dep'),
    
    # List views
    path('members/', views.member_list, name='member_list'),
    path('dependents/', views.dependent_list, name='dependent_list'),
    path('treasury/', views.treasury_list, name='treasury_list'),
    path('treasury-dep/', views.treasury_dep_list, name='treasury_dep_list'),
    path('activity-log/', ActivityLogView.as_view(), name='activity_log'),
    path('member/<int:pk>/edit/', views.MemberUpdateView.as_view(), name='edit_member'),
    path('api/member/<int:card_number>/payments/', views.member_payments, name='member_payments'),
    path('api/member/<int:card_number>/dependents/', views.member_dependents, name='member_dependents'),
    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('home/', views.home_view, name='home'),
    path('validate-card-number/', views.validate_card_number, name='validate_card_number'),
    path('api/member/<str:branch_member_number>/upload-picture/', views.upload_member_picture, name='upload_member_picture'),
    path('validate-card-number-add/', views.validate_card_number_add, name='validate_card_number_add'),
    path('api/dependent/<int:dependent_id>/payments/', views.dependent_payments, name='dependent_payments'),
    path('api/dependent/<int:dependent_id>/payments/', views.dependent_payments, name='dependent_payments'),
    path('signup/', views.signup_view, name='signup'),
    path('api/gender-distribution/', views.get_gender_distribution, name='gender_distribution'),
    path('upload-picture/', views.upload_picture, name='upload_picture'),





    
]

main_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


class MainMembers(models.Model):
    branch_member_number = models.CharField(max_length=255, null=True, blank=True, editable=False)
    card_number = models.IntegerField(db_column='Card_Number', primary_key=True)
    name = models.CharField(db_column='Name', max_length=100)
    surname = models.CharField(db_column='Surname', max_length=100)
    address = models.CharField(db_column='Address', max_length=100)
    phone_number = models.CharField(db_column='Phone_Number', max_length=45, blank=True, null=True)
    branch = models.CharField(db_column='Branch', max_length=100)
    gender = models.CharField(db_column='Gender', max_length=45)
    registration_year = models.IntegerField(db_column='Registration_Year', blank=True, null=True)
    number_of_dependants = models.IntegerField(db_column='Number_Of_Dependants')
    branch_member_number = models.CharField(db_column='Branch_Member_Number', max_length=10, unique=True)
    church_title = models.CharField(max_length=45, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'Main_Members'
        unique_together = (('card_number', 'name', 'surname'),)


class Dependents(models.Model):
    iddependents = models.AutoField(db_column='idDependents', primary_key=True)  # Field name made lowercase.
    card_number = models.IntegerField(db_column='Card_Number')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=100)  # Field name made lowercase.
    surname = models.CharField(db_column='Surname', max_length=100)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Dependents'


class Treasury(models.Model):
    idtreasury = models.AutoField(db_column='idTreasury', primary_key=True)  # Field name made lowercase.
    idmain_member = models.IntegerField(db_column='idMain_Member')  # Field name made lowercase.
    fund = models.CharField(db_column='Fund', max_length=45)  # Field name made lowercase.
    amount = models.IntegerField(db_column='Amount')  # Field name made lowercase.
    fund_date_year = models.IntegerField(db_column='Fund_Date_Year')  # Field name made lowercase.
    fund_date_month = models.CharField(db_column='Fund_Date_Month', max_length=50)  # Field name made lowercase.
    receipt_number = models.IntegerField(db_column='Receipt_Number')  # Field name made lowercase.
    payment_date = models.DateField(db_column='Payment_Date')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Treasury'
        unique_together = (('idmain_member', 'fund', 'fund_date_year', 'fund_date_month', 'receipt_number'),)


class TreasuryDep(models.Model):
    idtreasury_dep = models.AutoField(db_column='idTreasury_Dep', primary_key=True)  # Field name made lowercase.
    card_number = models.IntegerField(db_column='Card_Number')  # Field name made lowercase.
    dependent_id = models.IntegerField(db_column='Dependent_ID')  # Field name made lowercase.
    fund = models.CharField(db_column='Fund', max_length=50)  # Field name made lowercase.
    amount = models.IntegerField(db_column='Amount')  # Field name made lowercase.
    fund_date_year = models.IntegerField(db_column='Fund_Date_Year')  # Field name made lowercase.
    fund_date_month = models.IntegerField(db_column='Fund_Date_Month')  # Field name made lowercase.
    reciept_number = models.IntegerField(db_column='Reciept_Number')  # Field name made lowercase.
    payment_date = models.DateField(db_column='Payment_Date')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Treasury_Dep'
        
        


class ActivityLog(models.Model):
    ACTIONS = (
        ('CREATE', 'Created'),
        ('UPDATE', 'Updated'),
        ('DELETE', 'Deleted'),
        ('LOGIN', 'Logged In'),
        ('PAYMENT', 'Payment Made'),
    )

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=ACTIONS)
    timestamp = models.DateTimeField(auto_now_add=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    description = models.TextField()

    class Meta:
        ordering = ['-timestamp']
        
class MemberPictures(models.Model):
    id = models.AutoField(primary_key=True)
    branch_member_number = models.OneToOneField(MainMembers, to_field='branch_member_number', db_column='Branch_Member_Number', on_delete=models.CASCADE)
    picture_data = models.BinaryField(null=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'Member_Pictures'
        
class Picture(models.Model):
    image = models.ImageField(upload_to='pictures/')
    upload_date = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"Picture uploaded on {self.upload_date}"

    class Meta:
        ordering = ['-upload_date']
        
class Treasury(models.Model):
    FUND_CHOICES = [
        ('Annual', 'Annual'),
        ('Building Fund', 'Building Fund'),
        ('Thanksgiving', 'Thanksgiving'),
        ('Maintenance', 'Maintenance'),
        ('Blessing', 'Blessing'),
        ('Registration', 'Registration'),
    
    ]

    idtreasury = models.AutoField(db_column='idTreasury', primary_key=True)
    idmain_member = models.IntegerField(db_column='idMain_Member')
    fund = models.CharField(db_column='Fund', max_length=45, choices=FUND_CHOICES)
    amount = models.IntegerField(db_column='Amount')
    fund_date_year = models.IntegerField(db_column='Fund_Date_Year')
    fund_date_month = models.CharField(db_column='Fund_Date_Month', max_length=50)
    receipt_number = models.IntegerField(db_column='Receipt_Number')
    payment_date = models.DateField(db_column='Payment_Date')

    class Meta:
        managed = False
        db_table = 'Treasury'
        unique_together = (('idmain_member', 'fund', 'fund_date_year', 'fund_date_month', 'receipt_number'),)



    def __str__(self):
        return f"{self.user} {self.action} {self.content_type}"
    

main_app/forms.py
from django import forms
from .models import MainMembers, Dependents, Treasury, TreasuryDep

class MainMembersForm(forms.ModelForm):
    class Meta:
        model = MainMembers
        exclude = ['branch_member_number']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(choices=[('M', 'Male'), ('F', 'Female')], attrs={'class': 'form-control'}),
            'branch': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
        }

class DependentsForm(forms.ModelForm):
    class Meta:
        model = Dependents
        exclude = ['idDependents']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'card_number': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class TreasuryForm(forms.ModelForm):
    class Meta:
        model = Treasury
        fields = '__all__'
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'fund': forms.TextInput(attrs={'class': 'form-control'}),
            'payment_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'receipt_number': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class TreasuryDepForm(forms.ModelForm):
    class Meta:
        model = TreasuryDep
        fields = '__all__'
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'fund': forms.TextInput(attrs={'class': 'form-control'}),
            'payment_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'receipt_number': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        
# main_app/forms.py

class TreasuryForm(forms.ModelForm):
    FUND_CHOICES = [
        ('Annual', 'Annual'),
        ('Building Fund', 'Building Fund'),
        ('Thanksgiving', 'Thanksgiving'),
        ('Maintenance', 'Maintenance'),
        ('Blessing', 'Blessing'),
        ('Registration', 'Registration'),
    ]
    
    fund = forms.ChoiceField(choices=FUND_CHOICES)
    
    class Meta:
        model = Treasury
        fields = '__all__'

main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - HJCRSA</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0/dist/chartjs-plugin-datalabels.min.js"></script>
</head>
<body class="bg-gray-100">
    {% load static %}
    <div id="loading-indicator" class="hidden fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div class="bg-white p-6 rounded-lg shadow-xl flex items-center space-x-4">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            <span class="text-lg font-semibold text-gray-700">Loading...</span>
        </div>
    </div>    
    <!-- Sidebar -->
    <aside class="fixed top-0 left-0 w-64 h-full bg-white shadow-xl border-r border-gray-200 transition-all duration-300 ease-in-out" aria-label="Sidebar">
        <div class="h-full px-4 py-6 overflow-y-auto">
            <ul class="space-y-2">
                <li>
                    <a href="{% url 'home' %}" class="flex items-center p-3 text-gray-700 rounded-lg transition-all duration-200 ease-in-out hover:bg-blue-50 hover:text-blue-600 group">
                        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
                        </svg>
                        <span class="ml-4 font-medium text-sm">Home</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'member_list' %}" class="flex items-center p-3 text-gray-700 rounded-lg transition-all duration-200 ease-in-out hover:bg-blue-50 hover:text-blue-600 group">
                        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path>
                        </svg>
                        <span class="ml-4 font-medium text-sm">Members</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dependent_list' %}" class="flex items-center p-3 text-gray-700 rounded-lg transition-all duration-200 ease-in-out hover:bg-blue-50 hover:text-blue-600 group">
                        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                        </svg>
                        <span class="ml-4 font-medium text-sm">Dependents</span>
                    </a>
                </li>
                {% if perms.main_app.view_treasury %}
                <li>
                    <a href="{% url 'treasury_list' %}" class="flex items-center p-3 text-gray-700 rounded-lg transition-all duration-200 ease-in-out hover:bg-blue-50 hover:text-blue-600 group">
                        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                        <span class="ml-4 font-medium text-sm">Treasury</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'treasury_dep_list' %}" class="flex items-center p-3 text-gray-700 rounded-lg transition-all duration-200 ease-in-out hover:bg-blue-50 hover:text-blue-600 group">
                        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z"></path>
                        </svg>
                        <span class="ml-4 font-medium text-sm">Treasury Dependent</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'upload_picture' %}" class="flex items-center p-3 text-gray-700 rounded-lg transition-all duration-200 ease-in-out hover:bg-blue-50 hover:text-blue-600 group">
                        <svg class="w-6 h-6 text-gray-500 group-hover:text-blue-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                        </svg>
                        <span class="ml-4 font-medium text-sm">Load Picture</span>
                    </a>
                </li>                
                {% endif %}
            </ul>
        </div>
    </aside>
    <!-- Top Navigation Bar -->
    <nav class="fixed top-0 left-0 right-0 z-50 bg-white border-b border-gray-200 shadow-sm">
        <div class="flex items-center justify-between h-16 px-4 max-w-full mx-auto">
            <div class="flex items-center">
                <button id="toggleSidebar" class="mr-4 text-gray-600 hover:text-gray-900 lg:hidden">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
                    </svg>
                </button>
                <img src="{% static 'main_app/images/logo.png' %}" class="h-10 w-auto mr-4" alt="HJCRSA Logo" />
                <span class="text-base font-medium text-gray-700">Holy Jerusalem Church Of Repentance Of South Africa</span>
            </div>

            <!-- User Menu -->
            <div class="relative">
                <button type="button" class="flex items-center space-x-3 p-2 rounded-lg hover:bg-blue-50" id="user-menu-button">
                    <img class="w-8 h-8 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-5.jpg" alt="user photo">
                    <span class="hidden md:block text-sm text-gray-600">{{ user.username }}</span>
                </button>
                <!-- Dropdown menu -->
                <div id="user-dropdown" class="z-10 hidden absolute right-0 mt-2 w-48 bg-white divide-y divide-gray-100 rounded-lg shadow-lg">
                    <div class="px-4 py-3 text-sm text-gray-900">
                        <div>{{ user.first_name }} {{ user.last_name }}</div>
                        <div class="font-medium truncate">{{ user.email }}</div>
                    </div>
                    <ul class="py-2 text-sm text-gray-700">
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100">Profile</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100">Settings</a>
                        </li>
                    </ul>
                    <div class="py-1">
                        <a href="{% url 'logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Sign out</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- Main Content Area -->
    <main class="ml-64 mt-16 p-4">
        {% block content %}{% endblock %}
    </main>

    <script>
        // User Menu Dropdown Toggle
        const userMenuButton = document.getElementById('user-menu-button');
        const userDropdown = document.getElementById('user-dropdown');

        userMenuButton.addEventListener('click', () => {
            userDropdown.classList.toggle('hidden');
        });

        // Close dropdown when clicking outside
        document.addEventListener('click', (event) => {
            if (!userMenuButton.contains(event.target) && !userDropdown.contains(event.target)) {
                userDropdown.classList.add('hidden');
            }
        });

        // Sidebar Toggle for Mobile
        const toggleSidebar = document.getElementById('toggleSidebar');
        const sidebar = document.querySelector('aside');

        toggleSidebar.addEventListener('click', () => {
            sidebar.classList.toggle('-translate-x-full');
        });
    </script>
</body>
</html>